# Generated by Django 5.1.2 on 2025-01-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.IntegerField(choices=[(1, 'administrador'), (2, 'cliente'), (3, 'Proveedor')], default=2),
        ),
    ]
