# Generated by Django 5.1.2 on 2024-10-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrareserva',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
