# Generated by Django 5.1.2 on 2024-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_remove_alojamiento_reserva_alojamiento_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(),
        ),
    ]
