# Generated by Django 5.1.2 on 2025-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_cliente_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
