# Generated by Django 5.1.2 on 2024-12-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_alter_reserva_fecha_llegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
