# Generated by Django 5.1.1 on 2024-10-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_rename_conteseña_usuario_contrasenya'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciontarea',
            name='asignacion_tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.tarea'),
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='asignacion_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor_comentario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario_tarea',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestor.tarea'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='etiquetas_tarea',
            field=models.ManyToManyField(to='gestor.tarea'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='colaborador_proyecto', to='gestor.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador_proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador_tareas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestor.proyecto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuarios_asignados',
            field=models.ManyToManyField(related_name='tareas_asignadas', through='gestor.AsignacionTarea', to='gestor.usuario'),
        ),
    ]
