# Generated by Django 5.1.1 on 2024-10-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_comentario_comentario_tarea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaciontarea',
            name='asignacion_tarea',
        ),
        migrations.RemoveField(
            model_name='asignaciontarea',
            name='asignacion_usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor_comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario_tarea',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='etiquetas_tarea',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='creador_proyecto',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='creador_tareas',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tarea_proyecto',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='usuarios_asignados',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
